### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by arronmabrey** [killemov/Shift#1]
Do you have a demo or at least some screen shots avaible?

**Comment by killemov** [comment]
![shift_torrents](https://cloud.githubusercontent.com/assets/932370/12071321/fa568a5a-b0a5-11e5-919c-28adadfe0852.png)
![shift_session](https://cloud.githubusercontent.com/assets/932370/12071322/ff3b78fa-b0a5-11e5-9ee8-195593a59364.png)
