### ISSUE TITLE
Add registerProtocolHandler to support magnet: links

### ISSUE THREAD

**Issue by ColinHebert** [killemov/Shift#16]
It would be nice to have Shift handling the `magnet:` protocol directly.

See https://github.com/transmission/transmission/pull/349

**Comment by killemov** [comment]
I experimented with the protocolHandler a long time ago and it is not worth my trouble. Currently Shift works like drag, drop, done! Quoted from the linked pull request: "Cons: each magnet link clicked opens a new browser tab to the Web UI.". I have to confess that I did get it to work, but the experience of opening of a new Shift page every click on a magnet put me off. There may be a way to do it with a helper page, but again my resources are limited so dont't expect anything soon. Especially for this "nice to have" ...

**Comment by killemov** [comment]
Implemented!
