### ISSUE TITLE
ETA vs Done Date

### ISSUE THREAD

**Issue by mhbates** [killemov/Shift#18]
The instructions at the bottom of the manual work for showing the done/completed date of finished torrents, but not the ETA of torrents currently downloading. How do you show the ETA?

**Comment by killemov** [comment]
Changed README.md to show a proper example of ETA.

**Comment by mhbates** [comment]
Thank you! One thing to note for whoever does this, you'll need to also add this to the css:

```
col.eta {
  width: 152px;
}
```

**Comment by mhbates** [comment]
One more note: The ETA will be in UTC time, so it will need to be adjusted for your time zone. So if you're UTC-3, it would be:

`return seconds ? renderDateTime( (Date.now() / 1000 + seconds) - 10800 ) : "";`

Where the "- 10800" is 3 hours converted to seconds.
