### ISSUE TITLE
serving files

### ISSUE THREAD

**Issue by KamikazeePL** [killemov/Shift#19]
> Links Files and folders in torrents can be downloaded or displayed directly from Shift, even if the files are not 100% complete. Go to Session/Shift to configure a base URL to be used as a prefix for the content or folders, ftp://myname@myserver/mydownloads/ for example. To make the complete URLs work you still need to install and configure a web/ftp/... server such as Lighty to serve the file. Be warned that this is not for the novice user. For testing purposes you could use transmission-daemon itself to serve the linked file. You need file-system access and enough permissions for some clever file placement and/or symbolic linking to make that work, though. Hint: The files that make up the web interface for transmission-daemon are also stored somewhere on the server.

Could write something more about serving files by transmission-daemon.

**Comment by killemov** [comment]
Nope. The mentioned way of having transmission-daemon serving content is very risky. Use lighttpd instead.
