### ISSUE TITLE
release zip

### ISSUE THREAD

**Issue by SJ50** [killemov/Shift#20]
Please provide release zip to easy install and maintain docker container.
https://github.com/haugene/docker-transmission-openvpn/issues/1835

**Comment by killemov** [comment]
What's wrong with the zip created by Github itself? https://github.com/killemov/Shift/archive/refs/heads/master.zip

**Comment by pkishino** [comment]
Hello,
I would like to include this UI as per @SJ50 comment above, but for consistency and cleaner dependency management we would prefer a versioned/tagged release. It doesn't look like much activity has been ongoing here so I don't expect changes, but could you tag the current repo, that way we can pin the release, thanks

**Comment by Prikith** [comment]
you can just use the latest commit to get a zip, https://github.com/killemov/Shift/archive/25c897e3befcce4e2d4cf46a540f86aa4023dced.zip as an example

**Comment by killemov** [comment]
Yup. Easy enough.
