### ISSUE TITLE
Add batch path substitution for download location paths.

### ISSUE THREAD

**Issue by metaclam** [killemov/Shift#25]
Requested, as discussed here:

https://forum.transmissionbt.com/viewtopic.php?t=21198&sid=db7e625642a6585e22d4110387360bf7

A method to do batch substitution for download location paths, with arbitrary search and replace, such that, for example:

/Volumes/OldDrive/Books/a/b/c/file.epub

could be changed to point to, for example:
/Volumes/NewDrive/NewSubPath/Books/a/b/c/file.epub
/Users/user/Downloads/Torrents/Books/a/b/c/file.epub

… by searching and replacing the beginning of the path:

i.e. everything in:
/Volumes/OldDrive/Books/

is now here:
/Volumes/NewDrive/NewSubPath/Books/

**Comment by killemov** [comment]
You can access it with:
torrent context menu -> relocate -> substitute

Safest would be to copy/move content manually and then change the paths with Shift. It is a client-side operation so don't close Shift until it's done. Unfortunately I have not implemented an indicator for that yet.

**Comment by metaclam** [comment]
Wow -- totally f'n amazing. Thank you so much.  More in the Transmission forum threads.
