### ISSUE TITLE
Can't get list of torrents to appear.

### ISSUE THREAD

**Issue by deinfluence** [killemov/Shift#29]
This issue was originally posted [here](https://forum.transmissionbt.com/viewtopic.php?p=81414&sid=c33ea9fd4316e69bee8e447413f7dd85#p81414) on the Transmission forum.

I am using Firefox (v130.0) and turned on the Browser Console to try and capture anything but all I get is this:
![image](https://github.com/user-attachments/assets/c34aa494-9083-4940-b398-c9f2a8e977be)

Should I look somewhere else?

**Comment by killemov** [comment]
In your screenshot only 2 lines apply to Shift: the "Exited ..." message from shift.js and the "... Declaration dropped." warning from labels.css. Those are just fine.
The fatal error is from func.js and lot of warnings come from NetUtil.sys.mjs. This leads me to believe that you have some funky plugins running that interfere with normal operations.
AFAICT no AJAX calls were made to Transmission because there should be a HTTP 409 error in there. So where is that func.js error coming from?

**Comment by deinfluence** [comment]
I've disabled all my plugins and am just left with this:
![image](https://github.com/user-attachments/assets/0e794c31-0dce-46cd-8216-e57a8bbb4288)

Is there a way to debug shift.js?

**Comment by killemov** [comment]
> I've disabled all my plugins and am just left with this: 

That looks reasonable, still no HTTP 409 error though. (Any idea where that func.js error came from?)

> Is there a way to debug shift.js?

Yes, with the built-in developer tools.

Set a breakpoint ON and IN (next line below) the onloaded handler:
```JavaScript
document.observe( "dom:loaded", function() {
...
``` 
and step through it after reloading the page. (Or add the keyword [`debugger;`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger) one line before that line.) Also set breakpoints ON and IN every `dorequest` and `fetchTorrents` within the same handler. Because the program will appear to just skip over them if you don't. They are asynchronous calls to the "server" and so the code path temporarily splits logically.

I suspect there might be a network issue, but let's see. You can also see the network traffic in another tab of the developer tools.

**Comment by deinfluence** [comment]
I can't find the func.js - must have been another tab I had open at the time.

However, I am getting a 409 on the network console.

![image](https://github.com/user-attachments/assets/f5f69bfa-499b-4f78-a3e3-b009b07ee3f6)

**Comment by killemov** [comment]
AFAICT the console works per tab. The 409 indicates that there is communication. If you select XHR instead of Images you should see some more communication. Any insights from debugging?

**Comment by deinfluence** [comment]
The debugging side is a bit new to me. Is this the correct screen? How do I set the breakpoints for ON and IN?

![image](https://github.com/user-attachments/assets/73a2f1d4-5097-4977-89af-c2c15bc1b702)

**Comment by killemov** [comment]
> The debugging side is a bit new to me.

I caught that. If you had, you would have pointed me to an error before.

> Is this the correct screen?

Yes! :clap: 

> How do I set the breakpoints for ON and IN?

You have to read/understand more carefully and I probably have to spell things out more for you if we want to find out what is causing the problems.

I wrote:
> Set a breakpoint ON and IN (next line below) the onloaded handler:

First, you can set breakpoints by right-clicking on a line number and selecting "Add breakpoint". The onloaded (=event) handler is a function that runs when the document and all directly referenced resources has finished loading. With setting a breakpoint ON a handler I mean the line where the function is assigned to/called from the, in this case, observe call. With setting a breakpoint IN a handler I mean the first line within the function. As I mentioned before, this is the point where the program flow splits off.

Could you also post a screenshot of the network tab without any filters active?

**Comment by deinfluence** [comment]
Here is the screenshot of the network tab without any filters active:
![image](https://github.com/user-attachments/assets/2c9a142b-7ad3-4bea-a9c4-bf034140fc35)

With the breakpoints, I set them at:
- ON line 14 shift_gear.js
`document.observe( "dom:loaded", function() {`

- IN (on line 17) next available line after
`document.observe( "dom:loaded", function() {`

- ON each fetchTorrents (Lines 35, 63, 71) and each line after (Lines 36, 64, 72)

- I could not add breakpoints for every `doRequest` as they exist in `shift.js` and it won't allow me to add them, possibly because they are in a separate .js file.

If I have done this correctly, I am not sure what I should be looking for as it "steps" through.
![image](https://github.com/user-attachments/assets/3572199e-67b9-4fbb-8da9-b35a39ab75a1)

**Comment by killemov** [comment]
Screenshot of network activity shows no problems. :+1: The file shift_gear..js is for other developers to add their own functionality. The existing functions are there for illustration purposes. So the breakpoints should be placed in shift.js only. I can't think of a reason why breakpoints can't be placed at the start of the main onloaded handler. When you do step through the code and the next step leads you to an exception or an error then that is where it starts to get interesting. Good luck!

**Comment by deinfluence** [comment]
So I managed to fix it. 

Strangely it was related to setting the `TRANSMISSION_WEB_HOME` variable. I found by editing the `Info.plist` in the `Transmission.app` caused issues after reboot as macOS Sonoma would refuse to launch Transmission until I restored the original app from the Transmission website [probably because of gatekeeper] meaning I had to reset everything back each time. At the same experiencing the incomplete Shift webpage.

So I explored setting the variable persistently in the `.zshrc` file in the home directory. Once I set the variable there and did a refresh by running '/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user` and then launched Transmission the page loaded perfectly.

Now the key reason I wanted to use Shift was because I changed my NAS path [following the instructions [here](https://forum.transmissionbt.com/viewtopic.php?t=21198&start=15&sid=29b4ed33f03c86ee80d1a6972a122c6a) and [here](https://github.com/killemov/Shift/issues/29)]- I can't seem to find `relocate -> substitute` under the torrent context menu

Should I switch to the [TBT Forum post](https://forum.transmissionbt.com/viewtopic.php?t=21198&start=15&sid=29b4ed33f03c86ee80d1a6972a122c6a) or [Github issue](https://github.com/killemov/Shift/issues/29) for further help?

**Comment by killemov** [comment]
Let's just say I am having some mixed feelings about this. Glad you got it to work / mad macOS caused us unnecessary extra work. I will change the title of this issue to match.

`substitute` is a button on a dialog frame that opens when you click on the `relocate` menu item. Any user help questions go to the forum and any real issues go here of course.
