### ISSUE TITLE
Improvements for touch devices

### ISSUE THREAD

**Issue by pwatk** [killemov/Shift#5]
Hi,

I've come to the opinion that Shift is the best web UI for touch input but larger targets for certain elements would make it easier to use.

I'd most like to see larger toggle switches (or at least the area around them) for selecting torrents and changing settings as these are the smallest elements on the screen to hit.

I've also had a few issues with the 'add a torrent' window.

Whilst using an Android device it is impossible to paste a link in to the window because the keyboard pops up obscuring the window and hiding the 'Paste' context button.

This isn't an issue on an iOS device because the keyboard doesn't pop up whilst long pressing an input field.

Finally, this is just a UI fix but I've noticed that the backgroud of the 'add a torrent' window is misaligned whilst viewed on an Android or iOS device.
![add](https://f.cloud.github.com/assets/5104628/2013516/a57cf5a8-8796-11e3-9fc7-9045f2cec818.png)

**Comment by killemov** [comment]
Update: There is a more touch-friendly style-sheet available. It's called touch.css.
