### ISSUE TITLE
How do I use/install this?

### ISSUE THREAD

**Issue by peaveyman** [killemov/Shift#8]
I'm running Manjaro Linux. Will this run on my system?

**Comment by killemov** [comment]
Yes. Do you realize that Shift is supposed to be a replacement for the stock web interface (aka Clutch) of transmission-daemon?

In a nutshell:
* Download and unpack the archive from github or clone it with git.
* Stop transmission-daemon
* `export TRANSMISSION_WEB_HOME=/my/path/to/the/unzipped/dir`
* Start transmission-daemon

If this does not work you could try and replace the base folder where the official transmission-daemon web resources reside. ( `/usr/share/transmission/web` for example )
