### ISSUE TITLE
WebUI breaks in latest update.

### ISSUE THREAD

**Issue by zp** [killemov/Shift#9]
After updating to commit 761918b the **Torrents** tab doesn't appear to function at all for me, it doesn't load downloading torrents, and attempting to change status filter gives the following error.

- Uncaught TypeError: Cannot read property 'options' of undefined @ shift.js:1743
  - changeRequest @ shift.js:1743
  - setDefaultTorrentRequest @ shift.js:1759
  - (anonymous function) @ shift.js:1120
  - (anonymous function) @ prototype.js:7277

The error also happens when you switch to the session tab (appears to function correctly, can see all the options), and then click on the torrents tab to attempt to go back to torrent list. (doesn't actually switch to torrents tab)

If I downgrade to commit 9712a3d, the web ui functions normally.

OS: Windows 10
Browser: Chrome Version 47.0.2526.69 beta-m (64-bit)

**Comment by killemov** [comment]
Fixed in b655a3f.
